# Configuration that are shared between transformer and form


households:
  hot_water: # carrier used in application MdH: Could we change this into the name of the application: hot_water, space_heating (instead of useable_heat)
    coal: # should these carriers match the real carriers in the graph, or the carriers = %w[coal crude_oil natural_gas biomass solar_thermal electricity steam_hot_water notdefined] in line 1 of form.html.haml?
      - coal_boiler_households_energetic
    crude_oil: 
      - oil_boiler_households_energetic
    natural_gas:
      - gas_boiler_households_energetic 
      - cv_hot_water_households_energetic 
      - fuel_cell_chp_households_energetic 
      - micro_chp_hot_water_households_energetic
    biomass:
      - biomass_boiler_households_energetic
    electricity:
      - heatpump_boiler_households_energetic 
      - electric_boiler_households_energetic
    steam_hot_water:
      - heatpump_boiler_using_city_heat_households_energetic  

  useable_heat:
    coal:
      - heater_on_coal_households_energetic
    crude_oil:
      - heater_on_oil_households_energetic
    natural_gas:
      - gas_fired_heater_households_energetic 
      - central_heating_households_energetic
      - gasheatpump_households_energetic
      - micro_CHP_production_households
    electricity:
      - electric_heater_households_energetic
      - heatpump_addon_households_energetic
      - heatpump_households_energetic
      - heat_pump_with_chs_households_energetic

# put this in a separate namespace, so it doesnt mess up
# when iterating over households
output_shares:
  useable_heat: heating_demand_households_energetic
  hot_water: hot_water_devices_households_energetic    

heating_ambient_heat: 
  natural_gas:
    - gasheatpump_households_energetic
  electricity:
    - heatpump_addon_households_energetic
    - heatpump_households_energetic
    - heat_pump_with_chs_households_energetic
