# Configuration that are shared between transformer and form




households: # This is the configuration needed to create the tabs.
  space_heating: 
    carrier: useable_heat
    parents:
      useable_heat: heating_demand_households_energetic
    section:
      coal:
        - heater_on_coal_households_energetic
      crude_oil:
        - heater_on_oil_households_energetic
      network_gas:
        - gas_fired_heater_households_energetic 
        - central_heating_households_energetic
        - gasheatpump_households_energetic
        - micro_chp_space_heating_households
      biomass:
        - heater_on_biomass_households_energetic
      solar_thermal:
        - solar_panel_for_heating_households_energetic
      electricity:
        - electric_heater_households_energetic
        - heatpump_addon_households_energetic
        - heatpump_households_energetic
        - heat_pump_with_chs_households_energetic
      steam_hot_water:
        - heat_from_steam_hot_water_households_energetic

  hot_water:
    carrier: hot_water # Application hot_water has output carrier hot_water
    parents: 
      hot_water: hot_water_devices_households_energetic
    section:
      coal: # These carriers should match the real carriers in the graph
        - coal_boiler_households_energetic
      crude_oil: 
        - oil_boiler_households_energetic
      network_gas:
        - gas_boiler_households_energetic 
        - cv_hot_water_households_energetic 
        - fuel_cell_chp_households_energetic 
        - micro_chp_hot_water_households_energetic
      biomass:
        - biomass_boiler_households_energetic
      electricity:
        - heatpump_boiler_households_energetic 
        - electric_boiler_households_energetic
      steam_hot_water:
        - heatpump_boiler_using_city_heat_households_energetic  

  cooking:
    carrier: useable_heat
    parents:
      useable_heat: cooking_demand_households_energetic
    section:
      network_gas:
        - gas_stove_households_energetic
      biomass:
        - biomass_cooking_households_energetic
      electricity:
        - electric_stove_households_energetic
        - halogen_stove_households_energetic
        - induction_stove_households_energetic

  lighting:
    carrier: light
    parents:
      light: effective_lighting_demand_households_energetic
    section:
      electricity:
        - traditional_lighting_households_energetic
        - efficient_lighting_households_energetic
        - led_lighting_households_energetic

  cooling:
    carrier: cooling
    parents:
      # the parent for gasheatpump_cooling_households_energetic is different
      # but this does not work yet properly.
      #network_gas: cooling_demand_households_energetic
      # 
      # MdH: Aren't you mixing up parent and child here. I think the parent of the gasheatpump is cooling: cooling_demand_households_energetic
      cooling: electricity_for_cooling_households_energetic
    section: 
      network_gas:
        - gasheatpump_cooling_households_energetic
      electricity:
        - airco_households_energetic
        - heatpump_cooling_households_energetic
        - heatpump_ts_cooling_households_energetic


# Configure applications with ambient heat
ambient_heat:
  hot_water: # Application hot_water has output carrier hot_water
    electricity:
      - heatpump_boiler_households_energetic
  space_heating: # Application space_heating has output carrier useable_heat
    network_gas:
      - gasheatpump_households_energetic
    electricity:
      - heatpump_addon_households_energetic
      - heatpump_households_energetic
      - heat_pump_with_chs_households_energetic
  
