# Configuration that are shared between transformer and form


households: # This is the configuration needed to create the tabs.

  hot_water: # Application hot_water has output carrier hot_water
    coal: # These carriers should match the real carriers in the graph
      - coal_boiler_households_energetic
    crude_oil: 
      - oil_boiler_households_energetic
    network_gas:
      - gas_boiler_households_energetic 
      - cv_hot_water_households_energetic 
      - fuel_cell_chp_households_energetic 
      - micro_chp_hot_water_households_energetic
    biomass:
      - biomass_boiler_households_energetic
    electricity:
      - heatpump_boiler_households_energetic 
      - electric_boiler_households_energetic
    steam_hot_water:
      - heatpump_boiler_using_city_heat_households_energetic  

  useable_heat: # Application space_heating has output carrier useable_heat
    coal:
      - heater_on_coal_households_energetic
    crude_oil:
      - heater_on_oil_households_energetic
    network_gas:
      - gas_fired_heater_households_energetic 
      - central_heating_households_energetic
      - gasheatpump_households_energetic
      - micro_CHP_production_households
    biomass:
      - heater_on_biomass_households_energetic
    solar_thermal:
      - solar_panel_for_heating_households_energetic
    electricity:
      - electric_heater_households_energetic
      - heatpump_addon_households_energetic
      - heatpump_households_energetic
      - heat_pump_with_chs_households_energetic
    steam_hot_water:
      - heat_from_steam_hot_water_households_energetic

# put this in a separate namespace, so it doesnt mess up
# when iterating over households
application_parents:
  hot_water: hot_water_devices_households_energetic    
  useable_heat: heating_demand_households_energetic
  

# Configure applications with ambient heat
ambient_heat:    
  hot_water: # Application hot_water has output carrier hot_water
    electricity:
      - heatpump_boiler_households_energetic
  useable_heat: # Application space_heating has output carrier useable_heat
    network_gas:
      - gasheatpump_households_energetic
    electricity:
      - heatpump_addon_households_energetic
      - heatpump_households_energetic
      - heat_pump_with_chs_households_energetic
  
