:environment_air:
environment_air-(loss): {conversion: 1.0}
(loss)-environment_air: {conversion: 1.0}

:environment_earth:
environment_earth-(loss): {conversion: 1.0}
(loss)-environment_earth: {conversion: 1.0}

:environment_sun:
environment_sun-(loss): {conversion: 1.0}
(loss)-environment_sun: {conversion: 1.0}

:environment_water:
environment_water-(loss): {conversion: 1.0}
(loss)-environment_water: {conversion: 1.0}
