:environment_air:
  :co2_free: 0.0
environment_air-(loss): {conversion: 1.0}
(loss)-environment_air: {}

:environment_earth:
  :co2_free: 0.0
environment_earth-(loss): {conversion: 1.0}
(loss)-environment_earth: {}

:environment_sun:
  :co2_free: 0.0
environment_sun-(loss): {conversion: 1.0}
(loss)-environment_sun: {}

:environment_water:
  :co2_free: 0.0
environment_water-(loss): {conversion: 1.0}
(loss)-environment_water: {}
