:environment_air:
environment_air-(loss): {conversion: 1.0}
(loss)-environment_air: {}

:environment_earth:
environment_earth-(loss): {conversion: 1.0}
(loss)-environment_earth: {}

:environment_sun:
environment_sun-(loss): {conversion: 1.0}
(loss)-environment_sun: {}

:environment_water:
environment_water-(loss): {conversion: 1.0}
(loss)-environment_water: {}
