---
id: 900
update_type: settings
updateable_period: both
key: settings_enable_merit_order
max_value:   1.0
start_value: 0.0
min_value:   0.0
query: UPDATE(GRAPH(graph), enable_merit_order, USER_INPUT())
