# The output of this query can be used to set the new "capacity_of_energy_heat_heatpump_water_water_electricity" input.

- unit = MW
- query =
    SUM(
      PRODUCT(
        V(households_collective_heatpump_water_water_electricity, number_of_units),
        V(households_collective_heatpump_water_water_electricity, heat_output_capacity)
      ),
      PRODUCT(
        V(buildings_collective_heatpump_water_water_electricity, number_of_units),
        V(buildings_collective_heatpump_water_water_electricity, heat_output_capacity)
      )
    )
