# The output of this query can be used to set the new "capacity_of_energy_heat_burner_waste_mix" input.

- unit = MW
- query =
    PRODUCT(
      V(energy_heater_for_heat_network_waste_mix, number_of_units),
      V(energy_heater_for_heat_network_waste_mix, heat_output_capacity)
    )
