# The output of this query can be used to set the new "capacity_of_industry_heat_burner_lignite" input.

- unit = MW
- query =
    PRODUCT(
      V(energy_heater_for_heat_network_lignite, number_of_units),
      V(energy_heater_for_heat_network_lignite, heat_output_capacity)
    )
