# The output of this query can be used to set the new "capacity_of_energy_heat_burner_wood_pellets" input.

- unit = MW
- query =
    PRODUCT(
      V(energy_heater_for_heat_network_wood_pellets, number_of_units),
      V(energy_heater_for_heat_network_wood_pellets, heat_output_capacity)
    )
