# The output of this query is, among others, needed to set the new "capacity_of_energy_heat_well_geothermal" input.

- unit = MJ
- query =
    SUM(
      Q(steam_hot_water_production_of_geothermal_wells),
      NEG(Q(steam_hot_water_production_of_industry_heat_well_geothermal))
    )
