# The output of this query is, among others, needed to set the new "capacity_of_industry_heat_well_geothermal" input.

- unit = MJ
- query =
    MIN(
      Q(steam_hot_water_production_of_geothermal_wells),
      SUM(
        Q(heat_deficit_in_industry),
        NEG(Q(steam_hot_water_production_of_industry_heat_burner_coal)),
        NEG(Q(steam_hot_water_production_of_industry_heat_burner_crude_oil))
      )
    )
