# The output of this query is, among others, needed to set the new "capacity_of_energy_heat_burner_crude_oil" input.

- unit = MJ
- query =
    SUM(
      Q(steam_hot_water_production_of_industry_heat_burner_crude_oil),
      NEG(Q(steam_hot_water_production_of_energy_heater_for_heat_network_crude_oil))
    )
