---
share_setter:
  :"households_cooker_halogen_electricity-households_useful_demand_cooking_useable_heat@useable_heat": 0.220697663886884
  :"households_cooker_induction_electricity-households_useful_demand_cooking_useable_heat@useable_heat": 0.0827372320849149
  :"households_cooker_network_gas-households_useful_demand_cooking_useable_heat@useable_heat": 0.668953504169674
  :"households_cooker_resistive_electricity-households_useful_demand_cooking_useable_heat@useable_heat": 0.027611599858527
  :"households_cooker_wood_pellets-households_useful_demand_cooking_useable_heat@useable_heat": 0
  :"households_cooling_airconditioning_electricity-households_useful_demand_for_cooling_after_insulation@cooling": 0.9042
  :"households_cooling_heatpump_air_water_electricity-households_useful_demand_for_cooling_after_insulation@cooling": 0
  :"households_cooling_heatpump_ground_water_electricity-households_useful_demand_for_cooling_after_insulation@cooling": 0.0958
  :"households_collective_chp_biogas-households_final_demand_steam_hot_water@steam_hot_water": 0
  :"households_collective_chp_network_gas-households_final_demand_steam_hot_water@steam_hot_water": 0
  :"households_collective_chp_wood_pellets-households_final_demand_steam_hot_water@steam_hot_water": 0
  :"households_collective_geothermal-households_final_demand_steam_hot_water@steam_hot_water": 0
#  :"households_heat_network_connection_steam_hot_water-households_final_demand_steam_hot_water@steam_hot_water": 1
  :"households_space_heater_coal_aggregator-households_useful_demand_for_space_heating_after_insulation_and_solar_heater@useable_heat": 0.0005396562759842
  :"households_space_heater_combined_network_gas_aggregator-households_useful_demand_for_space_heating_after_insulation_and_solar_heater@useable_heat": 0.801103531566253
  :"households_space_heater_crude_oil_aggregator-households_useful_demand_for_space_heating_after_insulation_and_solar_heater@useable_heat": 0.0103460298589264
  :"households_space_heater_district_heating_steam_hot_water_aggregator-households_useful_demand_for_space_heating_after_insulation_and_solar_heater@useable_heat": 0
  :"households_space_heater_electricity_aggregator-households_useful_demand_for_space_heating_after_insulation_and_solar_heater@useable_heat": 0.0205027316692754
  :"households_space_heater_heatpump_air_water_electricity_aggregator-households_useful_demand_for_space_heating_after_insulation_and_solar_heater@useable_heat": 0.00332220189085481
  :"households_space_heater_heatpump_ground_water_electricity_aggregator-households_useful_demand_for_space_heating_after_insulation_and_solar_heater@useable_heat": 0.00332220189085481
  :"households_space_heater_hybrid_heatpump_air_water_electricity_aggregator-households_useful_demand_for_space_heating_after_insulation_and_solar_heater@useable_heat": 0.00149858366753674
  :"households_space_heater_micro_chp_network_gas_aggregator-households_useful_demand_for_space_heating_after_insulation_and_solar_heater@useable_heat": 0
  :"households_space_heater_network_gas_aggregator-households_useful_demand_for_space_heating_after_insulation_and_solar_heater@useable_heat": 0.0262328496285687
  :"households_space_heater_wood_pellets_aggregator-households_useful_demand_for_space_heating_after_insulation_and_solar_heater@useable_heat": 0.133132213551746
  :"households_water_heater_coal_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0
  :"households_water_heater_combined_network_gas_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0.882563721831907
  :"households_water_heater_crude_oil_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0
  :"households_water_heater_district_heating_steam_hot_water_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0
  :"households_water_heater_fuel_cell_chp_network_gas_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0
  :"households_water_heater_heatpump_air_water_electricity_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0.00274394050543448
  :"households_water_heater_heatpump_ground_water_electricity_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0.00304882278381609
  :"households_water_heater_hybrid_heatpump_air_water_electricity_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0.00105418504757753
  :"households_water_heater_micro_chp_network_gas_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat":  0
  :"households_water_heater_network_gas_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0.0287792517988665
  :"households_water_heater_resistive_electricity_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0.0818100780323984
  :"households_useful_demand_for_hot_water_after_solar_heater-households_useful_demand_hot_water@useable_heat": 0.9901
  :"households_useful_demand_for_hot_water_for_houses_with_solar_heater-households_useful_demand_hot_water@useable_heat": 0.0099
  :"households_water_heater_solar_thermal-households_useful_demand_for_hot_water_for_houses_with_solar_heater@useable_heat": 0.5
  :"households_useful_demand_for_hot_water_after_solar_heater-households_useful_demand_for_hot_water_for_houses_with_solar_heater@useable_heat": 0.5
  :"households_useful_demand_for_space_heating_after_insulation_and_solar_heater-households_useful_demand_for_space_heating_after_insulation@useable_heat": 0.9901
  :"households_useful_demand_for_space_heating_after_insulation_for_houses_with_solar_heater-households_useful_demand_for_space_heating_after_insulation@useable_heat": 0.0099
  :"households_useful_demand_for_space_heating_after_insulation_and_solar_heater-households_useful_demand_for_space_heating_after_insulation_for_houses_with_solar_heater@useable_heat": 0.85
  :"households_water_heater_solar_thermal-households_useful_demand_for_space_heating_after_insulation_for_houses_with_solar_heater@useable_heat": 0.15
  :"households_water_heater_wood_pellets_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0
  :"households_lighting_efficient_fluorescent_electricity-households_useful_demand_light@light": 0.485
  :"households_lighting_incandescent_electricity-households_useful_demand_light@light": 0.495
  :"households_lighting_led_electricity-households_useful_demand_light@light": 0.02
  :"households_solar_pv_solar_radiation-households_locally_available_electricity@electricity": 26109878.4

preset_demand_setter:
  households_useful_demand_cooking_useable_heat: 22380802.1135689
  households_appliances_clothes_dryer_electricity: 11492107.2
  households_appliances_computer_media_electricity: 15361898.4
  households_appliances_dishwasher_electricity: 9615844.8
  households_appliances_fridge_freezer_electricity: 34593588
  households_appliances_other_electricity: 13485636
  households_appliances_television_electricity: 15361898.4
  households_appliances_vacuum_cleaner_electricity: 7739582.4
  households_appliances_washing_machine_electricity: 9615844.8
  households_new_houses_useful_demand_for_cooling: 10719827.0748143
  households_old_houses_useful_demand_for_cooling: 51575392.3188262
  households_useful_demand_hot_water: 109537433.784274
  households_useful_demand_light: 1941818.18181818
  households_new_houses_useful_demand_for_heating: 119946508.177695
  households_old_houses_useful_demand_for_heating: 577088433.737171

conversion_setter:


number_of_units_setter:
